### ISSUE TITLE
MetaData correction

### ISSUE THREAD

**Issue by achamely** [binary-star-near/usdt-gold#11]
While i know its just for example purposes, to avoid confusion the decimal places should be set to 6 as that is one of the metadata items that can not be changed after creation
https://github.com/binary-star-near/usdt-gold/blob/main/src/lib.rs#L75

**Comment by fadeevab** [comment]
Agree. I'm about to fix it in a few hours.

**Comment by fadeevab** [comment]
Fixed here: 2e3c6996ec0bed0438b91541ec066640eb48d87a
